name: Update docker base
on:
  push:
    paths:
      - 'docker_base/**'
      - '.github/workflows/docker_base.yaml'

jobs:
  build:
    name: Build docker base image
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.23.0
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Release to Docker Fitter Base
        run: |
          DOCKER_TAG=ghcr.io/pxyup/fitter_base:latest
          docker buildx build --platform linux/arm64 -f ./docker_base/Dockerfile -t ${DOCKER_TAG} .
          docker login ghcr.io --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.TOKEN }} && docker push ${DOCKER_TAG}
