name: Docker CLI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-12
    steps:
      - run: |
          brew install docker
          colima start
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Build the Docker image
        run: docker build -t ghcr.io/pxyup/fitter:latest .
      - name: Docker Publish
        run: docker login ghcr.io --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.TOKEN }} && docker push ghcr.io/pxyup/fitter:latest